### ISSUE TITLE
ERROR INSTALLING p5bots-server

### ISSUE THREAD

**Issue by tanishqmanuja** [sarahgp/p5bots#31]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> npm install -g p5bots-server
C:\Users\lenovo\AppData\Roaming\npm\bots-go -> C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\app.js

> serialport@4.0.7 install C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.5.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release\serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.5.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:158:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
node-pre-gyp ERR! node -v v10.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\lenovo\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2018-07-10T05_19_49_360Z-debug.log
[2018-07-10T05_19_49_360Z-debug.log](https://github.com/sarahgp/p5bots/files/2178962/2018-07-10T05_19_49_360Z-debug.log)

**Comment by Guillaume-slize** [comment]
Same here

**Comment by guiphaniel** [comment]
Has anyone found a solution to this error? I have the same please : 

Microsoft Windows [version 10.0.17763.503]
(c) 2018 Microsoft Corporation. Tous droits réservés.

C:\Users\guilh>npm install -g p5bots-server
C:\Users\guilh\AppData\Roaming\npm\bots-go -> C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\app.js

> serialport@4.0.7 install C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'D:\\Programmes\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Users\\guilh\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.15.3 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release\serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.15.3 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.15.3 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Programmes\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Programmes\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\Programmes\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Programmes\\nodejs\\node.exe" "D:\\Programmes\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\guilh\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\guilh\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\build\\Release"
gyp ERR! cwd C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gypgyp ERR!  ERR!not ok configure error

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\Programmes\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\Programmes\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at D:\Programmes\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stacknode-pre-gyp     at FSReqWrap.oncomplete (fs.js:153:21)
 ERR!gyp  build errorERR!
 System Windows_NT 10.0.17763
node-pre-gyp gypERR!  ERR!stack  Error: Failed to execute 'D:\Programmes\nodejs\node.exe D:\Programmes\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release' (1)
command "D:\\Programmes\\nodejs\\node.exe" "D:\\Programmes\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\guilh\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=C:\\Users\\guilh\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\build\\Release"
node-pre-gyp gypERR!  stackERR!     at ChildProcess.<anonymous> (C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
 node-pre-gypcwd  C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
ERR!gyp  stackERR!     at ChildProcess.emit (events.js:189:13)
 node-pre-gypnode -v  v10.15.3
ERR!gyp  stackERR!     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp node-gyp -v v3.8.0
gyp ERR! ERR!  not ok
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "D:\\Programmes\\nodejs\\node.exe" "C:\\Users\\guilh\\AppData\\Roaming\\npm\\node_modules\\p5bots-server\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'D:\Programmes\nodejs\node.exe D:\Programmes\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\build\Release' (1)
npm WARN rollback Rolling back wrappy@1.0.2 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\guilh\AppData\Roaming\npm\node_modules\p5bots-server\node_modules\serialport\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\once\node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\guilh\AppData\Roaming\npm-cache\_logs\2019-05-22T17_31_53_126Z-debug.log

**Comment by 4songsoftranscendence** [comment]
Similar error here I think too. 

MacBook-Pro-4:~ michael$ npm install p5bots-server
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3

> serialport@4.0.7 install /Users/michael/node_modules/firmata/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   '/usr/local/bin/node',
node-pre-gyp verb cli   '/Users/michael/node_modules/firmata/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@12.13.1 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/michael/node_modules/firmata/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@12.13.1 (node-v72 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@12.13.1 (node-v72 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
  CXX(target) Release/obj.target/serialport/src/serialport.o
  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from In file included from ../src/serialport.cpp:6:
../src/serialport.cpp:6:
../src/./serialport_poller.h:13:24: error: no type named 'Handle' in namespace
      'v8'
../src/./serialport_poller.h:13:24: error: no type named 'Handle' in namespace
      'v8'
....... (I SHORTENED FOR BREVITY)
gypgyp  ERR!ERR!  stack Error: `make` failed with exit code: 2
stackgyp Error: `make` failed with exit code: 2
 ERR!gyp  ERR!stack stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp gyp ERR! ERR!stack      at ChildProcess.emit (events.js:210:5)
stack     at ChildProcess.emit (events.js:210:5)
gypgyp  ERR! ERR!stack stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gypgyp  ERR!ERR!  SystemSystem Darwin 17.2.0
 Darwin 17.2.0
gypgyp ERR!  ERR!command  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release"
command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release"
gyp ERR!gyp cwd  /Users/michael/node_modules/firmata/node_modules/serialport
ERR! cwdgyp /Users/michael/node_modules/firmata/node_modules/serialport
 ERR!gyp node -v  v12.13.1
gypERR!  node -vERR! v12.13.1
 node-gyp -v v5.0.5
gypgyp  ERR!ERR!  node-gyp -vnot ok v5.0.5
 
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/michael/node_modules/firmata/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 17.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/michael/node_modules/firmata/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/michael/node_modules/firmata/node_modules/serialport
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/michael/node_modules/firmata/node_modules/serialport/build/Release' (1)
npm WARN enoent ENOENT: no such file or directory, open '/Users/michael/package.json'
npm WARN michael No description
npm WARN michael No repository field.
npm WARN michael No README data
npm WARN michael No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serialport@4.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@4.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael/.npm/_logs/2019-11-30T21_04_33_344Z-debug.log
MacBook-Pro-4:~ michael$

**Comment by thoschneider** [comment]
Same here.
`node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-linux-x64.tar.gz `

serialport is not available at this location. It would be very nice if you could fix this.

**Comment by sapphire-cision** [comment]
I'm having the same issue on Mac:

```
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@12.16.2 (node-v72 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v72-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@12.16.2 (node-v72 ABI) (falling back to source compile with node-gyp) 
```

**Comment by jeremydouglass** [comment]
Your examples include urls with file names including -v64- or -v74-. If you look at the assets attached release 4.0.7, those urls are bad because files with those version numbers don't exist. The highest one is -v57-.

https://github.com/serialport/node-serialport/releases/4.0.7

**Comment by sapphire-cision** [comment]
Thanks for the link and suggestions, Jeremy. I ended up getting it to work just yesterday by using Node version 0.12.9 (using “nvm install 0.12.9”), but perhaps going into the code from the tutorial I was following and changing the v# will be a better solution!

**Comment by PatDeNerd** [comment]
Similar to what vrimages said, there is an easy fix (which I only found after hours of frustration), at least until this repo is updated.

Step 1: Uninstall node.js

Step 2: Go to https://nodejs.org/en/download/releases/

Step 3: Download “Node.js 8.17.0” and install it.

And... you’re done! Assuming you’ve followed all the other steps in the tutorials correctly, you should be able to install p5bots-server without any error from “serialport”.

**Comment by Jackademia** [comment]
> Similar to what vrimages said, there is an easy fix (which I only found after hours of frustration), at least until this repo is updated.
> 
> Step 1: Uninstall node.js
> 
> Step 2: Go to https://nodejs.org/en/download/releases/
> 
> Step 3: Download “Node.js 8.17.0” and install it.
> 
> And... you’re done! Assuming you’ve followed all the other steps in the tutorials correctly, you should be able to install p5bots-server without any error from “serialport”.

I'm currently on 8.17.0 and still having the same issue

**Comment by Jackademia** [comment]
> > Similar to what vrimages said, there is an easy fix (which I only found after hours of frustration), at least until this repo is updated.
> > Step 1: Uninstall node.js
> > Step 2: Go to https://nodejs.org/en/download/releases/
> > Step 3: Download “Node.js 8.17.0” and install it.
> > And... you’re done! Assuming you’ve followed all the other steps in the tutorials correctly, you should be able to install p5bots-server without any error from “serialport”.
> 
> I'm currently on 8.17.0 and still having the same issue

Seems to be solved by installing locally
